### ISSUE TITLE
Whack.

### ISSUE THREAD

**Issue by davidawad** [avdaredevil/Flappy-Shell#1]
You need to build something thats NOT powershell.

**Comment by avdaredevil** [comment]
Haha Lol, did you try it?

On Sun, May 10, 2015 at 6:13 PM, David Awad notifications@github.com
wrote:

> You need to build something thats NOT powershell.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/avdaredevil/Flappy-Shell/issues/1.

## 

—
Yours Sincerely,
Apoorv Verma.

**Comment by avdaredevil** [comment]
![image](https://cloud.githubusercontent.com/assets/5303018/19415444/6ab1c866-933e-11e6-8be5-b89638c79dfe.png)
